In [1]:
#  DATA SOURCE
# https://www.kaggle.com/saurabh00007/diabetescsv/data

In [1]:
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn

from sklearn.neural_network import MLPRegressor

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score


from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
# from xgboost import XGBClassifier
# from sklearn.metrics import plot_roc_curve

from sklearn.model_selection import StratifiedKFold
import matplotlib.pyplot as plt

from scipy import interp
import numpy as np
from sklearn.metrics import auc
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix

from sklearn.metrics import classification_report,confusion_matrix


from sklearn.preprocessing import StandardScaler

import pandas as pd
from sklearn.preprocessing import label_binarize

In [2]:
fName='GallStone_dataset-uci.csv'
df = pd.read_csv(fName) 
print(df.shape)
df.describe().transpose()

(319, 39)

,count,mean,std,min,25%,50%,75%,max
Gallstone Status,319.0,0.495298,0.500763,0.00,0.000,0.000000,1.000,1.00
Age,319.0,48.068966,12.114558,20.00,38.500,49.000000,56.000,96.00
Gender,319.0,0.492163,0.500724,0.00,0.000,0.000000,1.000,1.00
Comorbidity,319.0,0.335423,0.517340,0.00,0.000,0.000000,1.000,3.00
Coronary Artery Disease (CAD),319.0,0.037618,0.190568,0.00,0.000,0.000000,0.000,1.00
Hypothyroidism,319.0,0.028213,0.165841,0.00,0.000,0.000000,0.000,1.00
Hyperlipidemia,319.0,0.025078,0.156609,0.00,0.000,0.000000,0.000,1.00
Diabetes Mellitus (DM),319.0,0.134796,0.342042,0.00,0.000,0.000000,0.000,1.00
Height,319.0,167.156740,10.053030,145.00,159.500,168.000000,175.000,191.00
Weight,319.0,80.564890,15.709069,42.90,69.600,78.800000,91.250,143.50
Body Mass Index (BMI),319.0,28.877116,5.313707,17.40,25.250,28.300000,31.850,49.70
Total Body Water (TBW),319.0,40.587774,7.930235,13.00,34.200,39.800000,47.000,66.20
Extracellular Water (ECW),319.0,17.071160,3.161857,9.00,14.800,17.100000,19.400,27.80
Intracellular Water (ICW),319.0,23.634483,5.349332,13.80,19.300,23.000000,27.550,57.10
Extracellular Fluid/Total Body Water (ECF/TBW),319.0,42.212038,3.244470,29.23,40.075,42.000000,44.000,52.00
Total Body Fat Ratio (TBFR) (%),319.0,28.274984,8.444417,6.30,22.025,27.820000,34.810,50.92
Lean Mass (LM) (%),319.0,71.638245,8.437598,48.99,65.165,72.110000,77.850,93.67
Body Protein Content (Protein) (%),319.0,15.938809,2.334744,5.56,14.465,15.870000,17.430,24.81
Visceral Fat Rating (VFR),319.0,9.078370,4.332501,1.00,6.000,9.000000,12.000,31.00
Bone Mass (BM),319.0,2.803292,0.509467,1.40,2.400,2.800000,3.200,4.00
Muscle Mass (MM),319.0,54.273041,10.603833,4.70,45.800,53.900000,62.600,78.80
Obesity (%),319.0,35.850125,109.799718,0.40,13.900,25.600000,41.750,1954.00
Total Fat Content (TFC),319.0,23.487774,9.607607,3.10,17.000,22.600000,28.550,62.50
Visceral Fat Area (VFA),319.0,12.171599,5.262178,0.90,8.570,11.590000,15.100,41.00
Visceral Muscle Area (VMA) (Kg),319.0,30.403448,4.460530,18.90,27.250,30.408108,33.800,41.10
Hepatic Fat Accumulation (HFA),319.0,1.150470,1.059217,0.00,0.000,1.000000,2.000,4.00
Glucose,319.0,108.688715,44.848714,69.00,92.000,98.000000,109.000,575.00
Total Cholesterol (TC),319.0,203.495298,45.758501,60.00,172.000,198.000000,233.000,360.00
Low Density Lipoprotein (LDL),319.0,126.652351,38.541175,11.00,100.500,122.000000,151.000,293.00
High Density Lipoprotein (HDL),319.0,49.475549,17.718701,25.00,40.000,46.500000,56.000,273.00
Triglyceride,319.0,144.502163,97.904493,1.39,83.000,119.000000,172.000,838.00
Aspartat Aminotransferaz (AST),319.0,21.684953,16.697605,8.00,15.000,18.000000,23.000,195.00
Alanin Aminotransferaz (ALT),319.0,26.855799,27.884413,3.00,14.250,19.000000,30.000,372.00
Alkaline Phosphatase (ALP),319.0,73.112539,24.181069,7.00,58.000,71.000000,86.000,197.00
Creatinine,319.0,0.800611,0.176433,0.46,0.650,0.790000,0.920,1.46
Glomerular Filtration Rate (GFR),319.0,100.818903,16.971396,10.60,94.170,104.000000,110.745,132.00
C-Reactive Protein (CRP),319.0,1.853856,4.989591,0.00,0.000,0.215000,1.615,43.40
Hemoglobin (HGB),319.0,14.418182,1.775815,8.50,13.300,14.400000,15.700,18.80
Vitamin D,319.0,21.401411,9.981659,3.50,13.250,22.000000,28.060,53.10

In [3]:
target_column = ['Gallstone Status'] 
predictors = list(set(list(df.columns))-set(target_column))
df[predictors] = df[predictors]/df[predictors].max()
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Gallstone Status,319.0,0.495298,0.500763,0.000000,0.000000,0.000000,1.000000,1.0
Age,319.0,0.500718,0.126193,0.208333,0.401042,0.510417,0.583333,1.0
Gender,319.0,0.492163,0.500724,0.000000,0.000000,0.000000,1.000000,1.0
Comorbidity,319.0,0.111808,0.172447,0.000000,0.000000,0.000000,0.333333,1.0
Coronary Artery Disease (CAD),319.0,0.037618,0.190568,0.000000,0.000000,0.000000,0.000000,1.0
Hypothyroidism,319.0,0.028213,0.165841,0.000000,0.000000,0.000000,0.000000,1.0
Hyperlipidemia,319.0,0.025078,0.156609,0.000000,0.000000,0.000000,0.000000,1.0
Diabetes Mellitus (DM),319.0,0.134796,0.342042,0.000000,0.000000,0.000000,0.000000,1.0
Height,319.0,0.875166,0.052634,0.759162,0.835079,0.879581,0.916230,1.0
Weight,319.0,0.561428,0.109471,0.298955,0.485017,0.549129,0.635889,1.0
Body Mass Index (BMI),319.0,0.581028,0.106916,0.350101,0.508048,0.569416,0.640845,1.0
Total Body Water (TBW),319.0,0.613108,0.119792,0.196375,0.516616,0.601208,0.709970,1.0
Extracellular Water (ECW),319.0,0.614070,0.113736,0.323741,0.532374,0.615108,0.697842,1.0
Intracellular Water (ICW),319.0,0.413914,0.093684,0.241681,0.338004,0.402802,0.482487,1.0
Extracellular Fluid/Total Body Water (ECF/TBW),319.0,0.811770,0.062394,0.562115,0.770673,0.807692,0.846154,1.0
Total Body Fat Ratio (TBFR) (%),319.0,0.555282,0.165837,0.123723,0.432541,0.546347,0.683621,1.0
Lean Mass (LM) (%),319.0,0.764794,0.090078,0.523006,0.695687,0.769830,0.831109,1.0
Body Protein Content (Protein) (%),319.0,0.642435,0.094105,0.224103,0.583031,0.639661,0.702539,1.0
Visceral Fat Rating (VFR),319.0,0.292851,0.139758,0.032258,0.193548,0.290323,0.387097,1.0
Bone Mass (BM),319.0,0.700823,0.127367,0.350000,0.600000,0.700000,0.800000,1.0
Muscle Mass (MM),319.0,0.688744,0.134566,0.059645,0.581218,0.684010,0.794416,1.0
Obesity (%),319.0,0.018347,0.056192,0.000205,0.007114,0.013101,0.021366,1.0
Total Fat Content (TFC),319.0,0.375804,0.153722,0.049600,0.272000,0.361600,0.456800,1.0
Visceral Fat Area (VFA),319.0,0.296868,0.128346,0.021951,0.209024,0.282683,0.368293,1.0
Visceral Muscle Area (VMA) (Kg),319.0,0.739743,0.108529,0.459854,0.663017,0.739857,0.822384,1.0
Hepatic Fat Accumulation (HFA),319.0,0.287618,0.264804,0.000000,0.000000,0.250000,0.500000,1.0
Glucose,319.0,0.189024,0.077998,0.120000,0.160000,0.170435,0.189565,1.0
Total Cholesterol (TC),319.0,0.565265,0.127107,0.166667,0.477778,0.550000,0.647222,1.0
Low Density Lipoprotein (LDL),319.0,0.432261,0.131540,0.037543,0.343003,0.416382,0.515358,1.0
High Density Lipoprotein (HDL),319.0,0.181229,0.064904,0.091575,0.146520,0.170330,0.205128,1.0
Triglyceride,319.0,0.172437,0.116831,0.001659,0.099045,0.142005,0.205251,1.0
Aspartat Aminotransferaz (AST),319.0,0.111205,0.085629,0.041026,0.076923,0.092308,0.117949,1.0
Alanin Aminotransferaz (ALT),319.0,0.072193,0.074958,0.008065,0.038306,0.051075,0.080645,1.0
Alkaline Phosphatase (ALP),319.0,0.371130,0.122747,0.035533,0.294416,0.360406,0.436548,1.0
Creatinine,319.0,0.548364,0.120844,0.315068,0.445205,0.541096,0.630137,1.0
Glomerular Filtration Rate (GFR),319.0,0.763780,0.128571,0.080303,0.713409,0.787879,0.838977,1.0
C-Reactive Protein (CRP),319.0,0.042716,0.114968,0.000000,0.000000,0.004954,0.037212,1.0
Hemoglobin (HGB),319.0,0.766925,0.094458,0.452128,0.707447,0.765957,0.835106,1.0
Vitamin D,319.0,0.403040,0.187979,0.065913,0.249529,0.414313,0.528437,1.0

In [4]:
X = df[predictors]
Y = df[target_column]


scale = StandardScaler()
scaledX = scale.fit_transform(X)

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(scaledX, Y, test_size=0.10, random_state=40)
print(X_train.shape); 
print(X_test.shape)

(287, 38)
(32, 38)

In [6]:

def withoutCV(model, X_test, Y_test):

    # print('\n ******* Without CROSS-VALIDATION ******** \n')

    y_pred = model.predict( X_test)
    tn, fp, fn, tp = confusion_matrix(Y_test, y_pred).ravel()

    # conf_mat = [[ tp,  fn],
    #             [fp,  tn]]
    conf_mat = [[tn, fp],
                [fn, tp]]

    # print(conf_mat)
    acc = (tp+tn)/(tp+tn+fp+fn)
    # print("Accuracy: %0.4f" % (acc))
    sens = (tp)/(tp+fn)
    # print("Sensitivity/Recall: %0.4f" % (sens))
    spec = (tn)/(tn+fp)
    # print("Specificity: %0.4f" % (spec))
    prec = (tp)/(tp+fp)
    # print("prec: %0.4f" % (prec))
    result = " \t Sn: " + str(round(sens, 3)) + " \t Sp: " + str(round(spec,3)) + " \t Acc: " + str(round(acc,3)) + " \t Pr: " + str(round(prec,3))   
    return result
    

    # print(confusion_matrix(Y_test,y_pred))
    # print(classification_report(Y_test,y_pred))

In [7]:

def withCV(model, X_train, X_test, Y_train, Y_test):
    # print('\n ********** using CROSS-VALIDATION  ********** \n')
    y_pred = cross_val_predict(model, X, Y, cv=10)
    tn, fp, fn, tp = confusion_matrix(Y, y_pred).ravel()

    # conf_mat = [[ tp,  fn],
    #             [fp,  tn]]
    conf_mat = [[tn, fp],
                [fn, tp]]

    # print(conf_mat)
    acc = (tp+tn)/(tp+tn+fp+fn)
    # print("Accuracy: %0.4f" % (acc))
    sens = (tp)/(tp+fn)
    # print("Sensitivity/Recall: %0.4f" % (sens))
    spec = (tn)/(tn+fp)
    # print("Specificity: %0.4f" % (spec))
    prec = (tp)/(tp+fp)
    # print("prec: %0.4f" % (prec))
    result = " \t Sn: " + str(round(sens, 3)) + " \t Sp: " + str(round(spec,3)) + " \t Acc: " + str(round(acc,3)) + " \t Pr: " + str(round(prec,3))   
    return result
    
    # print(confusion_matrix(Y,y_pred))
    # print(classification_report(Y,y_pred))

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import GradientBoostingClassifier



# 2. Define model list
models = [
    ("DecisionTree", DecisionTreeClassifier() ), 
    ("LogisticRegression", LogisticRegression(random_state=0)),
    ("RandomForest", RandomForestClassifier(n_estimators=100) ),
    ("GradientBoostingClassifier ", GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0)), 
    ("ExtraTreeClassify" , ExtraTreesClassifier(n_estimators=10, max_depth=None,min_samples_split=2, random_state=0) ),
    ("SVMlinear" , SVC(kernel='linear', C=1.0, random_state=1) ), 
    ("SVMrbf" , SVC(kernel='rbf', random_state=1, gamma=0.10, C=10.0) ), 
    ("NB" , GaussianNB()), 
    
]

In [9]:
# 3. Train in a loop for WITHOUT CV
result= "";
 
# 3. Train in a loop without CV
result= "";
for name, model in models:
    print("\n  ****** Training FOR:    ", name , "************")
    model = model.fit(X_train, Y_train)
    result = result +  name + ": " + withoutCV(model, X_test, Y_test ) + " \n"
     
    
print(result)

  ****** Training FOR:     DecisionTree ************

  ****** Training FOR:     LogisticRegression ************

  ****** Training FOR:     RandomForest ************

  ****** Training FOR:     GradientBoostingClassifier  ************

/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

  ****** Training FOR:     ExtraTreeClassify ************

  ****** Training FOR:     SVMlinear ************

  ****** Training FOR:     SVMrbf ************

  ****** Training FOR:     NB ************
DecisionTree:  	 Sn: 0.632 	 Sp: 0.692 	 Acc: 0.656 	 Pr: 0.75
LogisticRegression:  	 Sn: 0.737 	 Sp: 0.923 	 Acc: 0.812 	 Pr: 0.933
RandomForest:  	 Sn: 0.737 	 Sp: 0.923 	 Acc: 0.812 	 Pr: 0.933
GradientBoostingClassifier :  	 Sn: 0.737 	 Sp: 0.769 	 Acc: 0.75 	 Pr: 0.824
ExtraTreeClassify:  	 Sn: 0.579 	 Sp: 0.846 	 Acc: 0.688 	 Pr: 0.846
SVMlinear:  	 Sn: 0.737 	 Sp: 0.923 	 Acc: 0.812 	 Pr: 0.933
SVMrbf:  	 Sn: 0.632 	 Sp: 0.769 	 Acc: 0.688 	 Pr: 0.8
NB:  	 Sn: 0.105 	 Sp: 1.0 	 Acc: 0.469 	 Pr: 1.0

/Users/tanviralam/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [10]:
# 3. Train in a loop for WITH CV
result= "";
for name, model in models:
    print("\n  ****** Training FOR:    ", name , "************")
    y_score = model.fit(X_train, Y_train)
    result = result +  name + ": " + withCV(model, X_train, X_test, Y_train, Y_test ) + " \n"
    

    
print(result)

  ****** Training FOR:     DecisionTree ************

  ****** Training FOR:     LogisticRegression ************

/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """

  ****** Training FOR:     RandomForest ************

/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

  ****** Training FOR:     GradientBoostingClassifier  ************

/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

  ****** Training FOR:     ExtraTreeClassify ************

  ****** Training FOR:     SVMlinear ************

/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

  ****** Training FOR:     SVMrbf ************

  ****** Training FOR:     NB ************
DecisionTree:  	 Sn: 0.658 	 Sp: 0.677 	 Acc: 0.668 	 Pr: 0.667
LogisticRegression:  	 Sn: 0.684 	 Sp: 0.739 	 Acc: 0.712 	 Pr: 0.72
RandomForest:  	 Sn: 0.722 	 Sp: 0.758 	 Acc: 0.74 	 Pr: 0.745
GradientBoostingClassifier :  	 Sn: 0.722 	 Sp: 0.696 	 Acc: 0.708 	 Pr: 0.699
ExtraTreeClassify:  	 Sn: 0.627 	 Sp: 0.764 	 Acc: 0.696 	 Pr: 0.723
SVMlinear:  	 Sn: 0.665 	 Sp: 0.764 	 Acc: 0.715 	 Pr: 0.734
SVMrbf:  	 Sn: 0.665 	 Sp: 0.758 	 Acc: 0.712 	 Pr: 0.729
NB:  	 Sn: 0.127 	 Sp: 0.963 	 Acc: 0.549 	 Pr: 0.769

/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [11]:

from sklearn.ensemble import StackingClassifier

n = "StackingClassifier"
estimators = [

    ('rf', RandomForestClassifier(n_estimators=10, random_state=42)) ,
    ('mylr' , LogisticRegression(random_state=0) ), 
    ('svrlinear', SVC(kernel='linear', C=1.0, random_state=1) ), 
    ('svrbf', SVC(kernel='rbf', random_state=1, gamma=0.10, C=10.0) ), 
#     ("GradientBoostingClassifier ", GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0)), 
#     ("ExtraTreeClassify" , ExtraTreesClassifier(n_estimators=10, max_depth=None,min_samples_split=2, random_state=0) ),
    
    
]

model = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression() )
print(n)

y_score = model.fit(X_train,Y_train)
#scores = cross_val_score(c, X_train, Y_train, cv=5, scoring='accuracy')
#scores = cross_val_score(c, X_train, Y_train, cv=5, scoring='balanced_accuracy')
result = "Stacking with CV" + ": " + withCV(model, X_train, X_test, Y_train, Y_test ) + " \n"
print(result)   

result = "Stacking -withoutCV" + ": " + withoutCV(model, X_test, Y_test ) + " \n"
print(result)    

# withoutCV(model, X_train, X_test, Y_train, Y_test )

StackingClassifier

/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tanviralam/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Stacking with CV:  	 Sn: 0.69 	 Sp: 0.795 	 Acc: 0.743 	 Pr: 0.768

Stacking -withoutCV:  	 Sn: 0.737 	 Sp: 0.923 	 Acc: 0.812 	 Pr: 0.933